// scripts/generate-lexikon.mjs
import { promises as fs } from 'fs';
import path from 'path';
const ROOT = process.cwd();
const LEX_DIR = path.join(ROOT, 'public', 'lexikon');

function toPosix(p){ return p.split(path.sep).join('/'); }
function getMimeByExt(name){
  const ext = name.toLowerCase().split('.').pop() || '';
  const map = {
    png:'image/png', jpg:'image/jpeg', jpeg:'image/jpeg', svg:'image/svg+xml', webp:'image/webp',
    pdf:'application/pdf', txt:'text/plain', md:'text/markdown', mp3:'audio/mpeg', mp4:'video/mp4'
  };
  return map[ext] || 'application/octet-stream';
}

async function walk(dir, rel='') {
  const acc = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    const relp = toPosix(path.join(rel, e.name));
    if (e.isDirectory()) {
      acc.push({ type:'dir', name:e.name, path:'/' + relp });
      acc.push(...await walk(full, relp));
    } else {
      const stat = await fs.stat(full);
      acc.push({
        type:'file',
        name:e.name,
        path:'/' + toPosix(rel),     // Ordnerpfad
        url:'/lexikon/' + relp,      // öffentliche URL
        size: stat.size,
        modified: stat.mtimeMs,
        mime: getMimeByExt(e.name),
      });
    }
  }
  return acc;
}

function derivePaths(items){
  // Baue alle „schönen“ Routen aus Ordnern zusammen
  const paths = new Set();
  items.filter(i=>i.type==='dir').forEach(d=>{
    const slug = d.path.split('/').filter(Boolean); // ["Pferde","…"]
    paths.add(JSON.stringify({ params:{ slug } }));
  });
  // Auch für Ordner, die nur Dateien enthalten (falls kein dir-Eintrag existiert)
  items.filter(i=>i.type==='file').forEach(f=>{
    const slug = f.path.split('/').filter(Boolean);
    if(slug.length) paths.add(JSON.stringify({ params:{ slug } }));
  });
  return Array.from(paths).map(s=>JSON.parse(s));
}

async function main(){
  // Wenn kein lexikon-Verzeichnis existiert → leeres Manifest
  let items = [];
  try {
    const abs = LEX_DIR;
    await fs.access(abs);
    items = await walk(abs, '');
  } catch {
    items = [];
  }

  // Manifest speichern
  const manifest = { generatedAt: Date.now(), items };
  await fs.writeFile(path.join(ROOT, 'public', 'lexikon_manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');

  // getStaticPaths-Liste schreiben
  const paths = derivePaths(items);
  const ts = `// AUTO-GENERATED by scripts/generate-lexikon.mjs
export const lexikonPaths = ${JSON.stringify(paths, null, 2)} as const;
`;
  await fs.writeFile(path.join(ROOT, 'src', 'data', 'lexikon_paths.ts'), ts, 'utf8');
  console.log(`Generated ${items.length} entries, ${paths.length} pretty paths.`);
}
main().catch(e=>{ console.error(e); process.exit(1); });
