// AUTO-GENERATED by scripts/generate-lexikon.mjs
export const lexikonPaths = [
  {
    "params": {
      "slug": [
        "Ausland"
      ]
    }
  },
  {
    "params": {
      "slug": [
        "Deutschland"
      ]
    }
  },
  {
    "params": {
      "slug": [
        "Pferd"
      ]
    }
  },
  {
    "params": {
      "slug": [
        "Schildkroete"
      ]
    }
  },
  {
    "params": {
      "slug": [
        "Tauben"
      ]
    }
  },
  {
    "params": {
      "slug": [
        "Tierschutz"
      ]
    }
  },
  {
    "params": {
      "slug": [
        "Vermittlung"
      ]
    }
  }
] as const;
