// AUTO-GENERATED by scripts/generate-lexikon.mjs
export const lexikonPaths = [
  {
    "params": {
      "slug": "Ausland"
    }
  },
  {
    "params": {
      "slug": "Ausland/Kroatien"
    }
  },
  {
    "params": {
      "slug": "Ausland/Rumaenien"
    }
  },
  {
    "params": {
      "slug": "Ausland/Tuerkei"
    }
  },
  {
    "params": {
      "slug": "Deutschland"
    }
  },
  {
    "params": {
      "slug": "Deutschland/Hund"
    }
  },
  {
    "params": {
      "slug": "Deutschland/Igel"
    }
  },
  {
    "params": {
      "slug": "Deutschland/Maulkorb"
    }
  },
  {
    "params": {
      "slug": "Deutschland/Nutztier"
    }
  },
  {
    "params": {
      "slug": "Deutschland/Tauben"
    }
  },
  {
    "params": {
      "slug": "Deutschland/Vögel"
    }
  },
  {
    "params": {
      "slug": "Pferd"
    }
  },
  {
    "params": {
      "slug": "Sonstiges"
    }
  },
  {
    "params": {
      "slug": "Sonstiges/Podcasterinnen"
    }
  },
  {
    "params": {
      "slug": "Tierschutz"
    }
  },
  {
    "params": {
      "slug": "Tierschutz/Artengeschützte Tiere"
    }
  },
  {
    "params": {
      "slug": "Tierschutz/Herz & Pfote"
    }
  },
  {
    "params": {
      "slug": "Tierschutz/Katzenschutz"
    }
  },
  {
    "params": {
      "slug": "Tierschutz/Tierheim Forchheim"
    }
  },
  {
    "params": {
      "slug": "Tierschutz/Tierleid"
    }
  }
] as const;
